import battle_maps as m

HALLWAY = m.hallway()
CAVE = m.cave()
BOX = m.box()
TRAPEZIOD = m.trapezoid()
OCTAGON = m.octagon()
TRIANGLE = m.triangle()
FOX = m.fox()

TS = 2 #Tank size
TEAM_SIZE = 8
RESPAWN_TIME = 10
BACKGROUND_COLOR = "#abb0b6"#"#120505"
BATTLEFIELD_LENGTH = 500
INIT_WINDOW_WIDTH = BATTLEFIELD_LENGTH + 50
INIT_WINDOW_HEIGHT = BATTLEFIELD_LENGTH + 50
OFF_SCREEN = (INIT_WINDOW_HEIGHT**2 + INIT_WINDOW_WIDTH**2)**.5
WALL_BOUND = 5
MAP = OCTAGON
TURTLE_UPDATE_RATE = 30
DEV_PRINT_TIMER = 30
CLASS_LIST = ["Spawn", "Sniper", "Scout", "Tank"]

user_class_copy = None
user_tank_list = []
friendly_projectile_list = []
enemy_projectile_list = []
enemy_tank_list = []
wall_list = []
rocks = []

ROCK = [(0,.2), (.2,.1), (.1,-.14), (0,-.2), (-.12,.1), (-.1,.18), (0,.2)]
NUMBER_OF_ROCKS = 4
X_ROCK_AREA = 100
Y_ROCK_AREA = 60
ROCK_HP = 3

PROJECTILE_WALL_COLLISION = 4
TANK_SHELL_COLOR = "#202020"
TANK_SHELL = ((0,3*TS),(1*TS,0),(1*TS,-1*TS),(-1*TS,-1*TS),(-1*TS,0),(0,3*TS))
TANK_SHELL_SPEED = 3*TS
TANK_SHELL_HP = .9
TANK_SHELL_RANGE = 100 * TS
TANK_SHELL_CHANCE = 30
TANK_SHELL_FIRE_RATE = 50

BULLET_COLOR = "#303030"
BULLET = ((0,0),(0,1*TS),(1*TS,1*TS),(1*TS,0),(0,0))
BULLET_SPEED = 5*TS
BULLET_HP = .16
BULLET_RANGE = 75 * TS
BULLET_CHANCE = 20
BULLET_FIRE_RATE = 10

SNIPER_SHELL_COLOR = "#707070"
SNIPER_SHELL = ((0,4*TS),(.6*TS,-1*TS),(.8*TS,-1.2*TS),(-.8*TS,-1.2*TS),(-.6*TS,-1*TS),(0,4*TS))
SNIPER_SHELL_SPEED = 6*TS
SNIPER_SHELL_HP = 2
SNIPER_SHELL_RANGE = 150 * TS
SNIPER_SHELL_CHANCE = 70
SNIPER_SHELL_FIRE_RATE = 120

GUNNER_SHELL_COLOR = "#151515"
GUNNER_SHELL = ((0,2*TS),(.4*TS,-1*TS),(.6*TS,-1.2*TS),(-.6*TS,-1.2*TS),(-.4*TS,-1*TS),(0,2*TS))
GUNNER_SHELL_SPEED = 4.5*TS
GUNNER_SHELL_HP = .03
GUNNER_SHELL_RANGE = 75 * TS
GUNNER_SHELL_CHANCE = 70
GUNNER_SHELL_FIRE_RATE = 3

TANK = ((.1,8*TS),(.2*TS,4*TS),(2*TS,4*TS),(3*TS,3*TS),(3*TS,-1.7*TS),(1.8*TS,-3.5*TS),(-1.8*TS,-3.5*TS),(-3*TS,-1.7*TS),(-3*TS,3*TS),(-2*TS,4*TS),(-.2*TS,4*TS),(-.1,8*TS))
TANK_HP = 2
TANK_START = (0,0)
TANK_SPEED = 1
TANK_CHANCE = 32.5 #0 to 100
TANK_HEADING = 0
TANK_COLLISION = 6*TS
TANK_TURN_RATE = 5
TANK_ATTACK_RANGE = 150
TANK_MINIMUM_RANGE = 60
TANK_FIRE_TOLORANCE = 4
TANK_FIRE_RATE = 1

SPAWN = ((0,10*TS),(.2*TS,9*TS),(4*TS,6*TS),(6*TS,3*TS),(5*TS,-4*TS),(4*TS,-6*TS),(-4*TS,-6*TS),(-5*TS,-4*TS),(-6*TS,3*TS),(-4*TS,6*TS),(-.2*TS,9*TS),(0,10*TS))
SPAWN_HP = TANK_HP*10
SPAWN_START = (0,0)
SPAWN_HEADING = 0
SPAWN_SPEED = TANK_SPEED * .3
SPAWN_HEADING = TANK_HEADING
SPAWN_COLLISION = TS * 8
SPAWN_TURN_RATE = TANK_TURN_RATE * .3
SPAWN_ATTACK_RANGE = TANK_ATTACK_RANGE * 2
SPAWN_MINIMUM_RANGE = TANK_ATTACK_RANGE * 2
SPAWN_STOP_TRIGGER = 20
SPAWN_SLOW_SPEED = SPAWN_SPEED * .5

SCOUT = ((.1,4.5*TS),(.1*TS,3.5*TS),(1*TS,3*TS),(2*TS,2.5*TS),(1.5*TS,-1*TS),(1*TS,-1.3*TS),(-1*TS,-1.3*TS),(-1.5*TS,-1*TS),(-2*TS,2.5*TS),(-1*TS,3*TS),(-.1*TS,3.5*TS),(-.1,4.5*TS))
SCOUT_START = (-200,0)
SCOUT_COLOR = "pink"
SCOUT_CHANCE = 32.6 #0 to 100
SCOUT_TANK_HEADING = TANK_HEADING
SCOUT_TANK_HP = TANK_HP * .9
SCOUT_TANK_SPEED = TANK_SPEED * 3
SCOUT_TANK_TURN = TANK_TURN_RATE * 1.5
SCOUT_ATTACK_RANGE = TANK_ATTACK_RANGE * 1.2
SCOUT_MAX_TURN_SPEED = TANK_TURN_RATE * 2
SCOUT_MINIMUM_RANGE = TANK_MINIMUM_RANGE * 1.7
SCOUT_COLLISION = 3*TS

SNIPER = ((.3*TS,8*TS),(.3*TS,3*TS),(3*TS,4*TS),(4*TS,3*TS),(3*TS,-1.7*TS),(.4*TS,-4*TS),(-.4*TS,-4*TS),(-3*TS,-1.7*TS),(-4*TS,3*TS),(-3*TS,4*TS),(-.3*TS,3*TS),(-.3*TS,8*TS))
SNIPER_START = (-200,0)
SNIPER_COLOR = "orange"
SNIPER_CHANCE = 10 #0 to 100
SNIPER_TANK_HEADING = TANK_HEADING
SNIPER_TANK_HP = TANK_HP * .5
SNIPER_TANK_SPEED = TANK_SPEED * .4
SNIPER_ATTACK_RANGE = TANK_ATTACK_RANGE * 1.5
SNIPER_MAX_TURN_SPEED = TANK_TURN_RATE * .5
SNIPER_TANK_TURN = SNIPER_MAX_TURN_SPEED
SNIPER_MINIMUM_RANGE = TANK_MINIMUM_RANGE * 3
SNIPER_COLLISION = 6.5*TS

GUNNER = ((.2*TS,4*TS),(.3*TS,1.7*TS),(3*TS,2*TS),(4*TS,1*TS),(3*TS,-1.7*TS),(.4*TS,-4*TS),(-.4*TS,-4*TS),(-3*TS,-1.7*TS),(-4*TS,1*TS),(-3*TS,2*TS),(-.3*TS,1.7*TS),(-.2*TS,4*TS))
GUNNER_START = (-200,0)
GUNNER_COLOR = "orange"
GUNNER_CHANCE = 25 #0 to 100
GUNNER_TANK_HEADING = TANK_HEADING
GUNNER_TANK_HP = TANK_HP * 2
GUNNER_TANK_SPEED = TANK_SPEED * .8
GUNNER_ATTACK_RANGE = TANK_ATTACK_RANGE * .8
GUNNER_MAX_TURN_SPEED = TANK_TURN_RATE * .8
GUNNER_TANK_TURN = GUNNER_MAX_TURN_SPEED
GUNNER_MINIMUM_RANGE = TANK_MINIMUM_RANGE * 1
GUNNER_COLLISION = 5*TS

AIMER = ((0,2), (1,1), (1,0), (0,-1), (-1,-1), (-2,0), (-2,1), (-1,2))
AIMER_STEP_SIZE = 3
USER_HAS_AIMER = False
USER_AIMER_LENGTH = TANK_ATTACK_RANGE
USER_AIMER_COLOR1 = "dark green"#"#951500"
USER_AIMER_COLOR2 = "black"#"#951500"
USER_TANK_COLOR = "#252529"
USER_TANK_CONTROLS = ["Left", "Right", "Up", "Down", "f", "g", "c"]
USER_TANK_TURN_SPEED = TANK_TURN_RATE
USER_TANK_FORWARD_SPEED = TANK_SPEED * 1.2
USER_TANK_HP = TANK_HP * 2
USER_SHELL_FIRE_RATE = TANK_FIRE_RATE * .5
USER_BULLET_FIRE_RATE = TANK_FIRE_RATE * .2

ENEMY_START = (200,0)
ENEMY_TANK_HEADING = TANK_HEADING
ENEMY_COLOR = "red"
ENEMY_TANK_HP = TANK_HP * 1
ENEMY_TANK_SPEED = TANK_SPEED * 1
ENEMY_TANK_TURN = TANK_TURN_RATE * 1
ENEMY_ATTACK_RANGE = TANK_ATTACK_RANGE * 1
ENEMY_FIRE_RATE = TANK_FIRE_RATE * 1
ENEMY_MAX_TURN_SPEED = TANK_TURN_RATE * 1
ENEMY_MINIMUM_RANGE = TANK_MINIMUM_RANGE * 1

FRIENDLY_START = (-200,0)
FRIENDLY_COLOR = "blue"
FRIENDLY_TANK_HEADING = TANK_HEADING
FRIENDLY_TANK_HP = TANK_HP * 1
FRIENDLY_TANK_SPEED = TANK_SPEED * 1
FRIENDLY_TANK_TURN = TANK_TURN_RATE * 1
FRIENDLY_ATTACK_RANGE = TANK_ATTACK_RANGE * 1
FRIENDLY_FIRE_RATE = TANK_FIRE_RATE * 1
FRIENDLY_MAX_TURN_SPEED = TANK_TURN_RATE * 1
FRIENDLY_MINIMUM_RANGE = TANK_MINIMUM_RANGE * 1

ENEMY_SPAWN_HP = SPAWN_HP
ENEMY_SPAWN_HEADING = SPAWN_HEADING + 10
ENEMY_SPAWN_SPEED = SPAWN_SPEED
ENEMY_SPAWN_TURN = SPAWN_TURN_RATE
ENEMY_SPAWN_ATTACK_RANGE = SPAWN_ATTACK_RANGE
ENEMY_SPAWN_MAX_TURN_SPEED = SPAWN_TURN_RATE
ENEMY_SPAWN_TRIGGER = TEAM_SIZE * 1

FRIENDLY_SPAWN_HP = SPAWN_HP
FRIENDLY_SPAWN_HEADING = SPAWN_HEADING + 170
FRIENDLY_SPAWN_SPEED = SPAWN_SPEED
FRIENDLY_SPAWN_TURN = SPAWN_TURN_RATE
FRIENDLY_SPAWN_ATTACK_RANGE = SPAWN_ATTACK_RANGE
FRIENDLY_SPAWN_MAX_TURN_SPEED = SPAWN_TURN_RATE
FRIENDLY_SPAWN_TRIGGER = TEAM_SIZE * 1

def TANK_DEATH(tank):
    tank.ht()
    tank.clear()
    if tank in enemy_tank_list:
        enemy_tank_list.remove(tank)
    if tank in user_tank_list:
        user_tank_list.remove(tank)
            
def REMOVE_WALL(wall):
    wall.turt.clear()
    if wall in wall_list:
        wall_list.remove(wall)


def REMOVE_PROJECTILE(projectile, hit):
    if not hit:
        projectile.ht()
        if projectile in friendly_projectile_list:
            friendly_projectile_list.remove(projectile)
        if projectile in enemy_projectile_list:
            enemy_projectile_list.remove(projectile)
    else:
        projectile.ht()
        if projectile in friendly_projectile_list:
            friendly_projectile_list.remove(projectile)
        if projectile in enemy_projectile_list:
            enemy_projectile_list.remove(projectile)

def SMALL_EXPLOSION():
    pass

def BIG_EXPLOSION():
    pass
